#autoload :VIXFuturesCBOEHistoricalDataPull, 'market_data_pull/vix_futures_cboe_historical_data_pull'
require 'market_data_pull/vix_futures_cboe_historical_data_pull'
require 'market_data_pull/vix_central_screenshot'